# Generated by Django 5.0.2 on 2024-11-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports_analytics', '0001_initial'),
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='student_management.student'),
        ),
    ]
