# Generated by Django 5.0.2 on 2024-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent_portal', '0001_initial'),
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='student_management.student'),
        ),
    ]
